### PR TITLE
rough example of BusTrip (Process) to discuss

### PR DESCRIPTION
**Pull request by elf-pavlik**
by no means 'the way it should work' but just a concrete example around which we can focus our conversations.

i plan to add two drawings of serialized here directed label graph, one with qualified relations and one with direct ('collapsed'?) relations...

### CODE REVIEW

**Comment by elf-pavlik** [comment]
first attempt at drawing a graph, for now with direct relations(hips) (all qualified one collapsed)

BusTrip (collapsed)

now also graph with reified relations, this way we can use them as qualified relations
BusTrip (full)

please notice that instances of rdf:Property usually get used as labels for edges but sometimes as nodes (object of vf:relationship)

**Comment by elf-pavlik** [comment]
now also with reified/qualified relations

**Comment by ahdinosaur** [comment]
@elf-pavlik sweet, thanks for the example.

@bhaugen @fosterlynn: how would y'all model this? related to [valueflows/use-cases/bus-trip](https://github.com/valueflows/valueflows/blob/master/use-cases/bus-trip.md).

**Comment by elf-pavlik** [comment]
I shared with you all GDrive folder with original drawings...
Later I will enhance this drawing adding besides outputs which one can consider beneficial, an output which one can consider harmful - CO2 emission!

**Comment by elf-pavlik** [comment]
approach I used here looks very similar to OVN REA
- https://github.com/valueflows/process/blob/master/examples/bus-trip-paris-lille.jsonld#L72
- https://github.com/valueflows/process/blob/master/examples/bus-trip-paris-lille.jsonld#L83
- https://github.com/valueflows/process/blob/master/examples/bus-trip-paris-lille.jsonld#L93

matches
- https://github.com/valnet/valuenetwork/blob/master/docs/core_model.txt#L151
- https://github.com/valnet/valuenetwork/blob/master/docs/core_model.txt#L149

as well as
- https://github.com/valueflows/process/blob/master/examples/bus-trip-paris-lille.jsonld#L57

matches
- https://github.com/valnet/valuenetwork/blob/master/docs/core_model.txt#L152

plus
- https://github.com/valueflows/process/blob/master/examples/bus-trip-paris-lille.jsonld#L42

matches
- https://github.com/valnet/valuenetwork/blob/master/docs/core_model.txt#L149

Of course we need to iterate on it but already looks rather similar :smile:

**Comment by ahdinosaur** [comment]
> Of course we need to iterate on it but already looks rather similar :smile:

yay, @elf-pavlik i appreciate you trying to match REA / the NRP core model, more than happy to keep on iterating with these examples. :dancer:

**Comment by elf-pavlik** [comment]
> yay, @elf-pavlik i appreciate you trying to match REA / the NRP core model, more than happy to keep on iterating with these examples.

@ahdinosaur thanks!

While I notice that we all seem to 'wear different goggles' :eyeglasses: and perceive same things sometimes quite differently. We still do work on this **together** and need to make effort to understand how others look at those common things and how they may see them :eyes:

**Comment by ahdinosaur** [comment]
@elf-pavlik agreed. i'm happy we're all collaborating together with each of our different perspectives, it's better for everyone when we engage a diverse view of the problems we're trying to solve (["Linus's law"](http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html)). so i mean the best, even though i clearly have strong opinions on some things.

**Comment by fosterlynn** [comment]
ditto, ditto, ditto, and ditto!

**Comment by bhaugen** [comment]
@elf-pavlik - your comment comparing fragments of your jsonld file to fragments of the NRP core vocab was really useful. I found the jsonld easier to follow than the diagram.

I think you are very close.  

Here's my first issue with your jsonld and overall schema. [edit: Let's call this the Event Behavior issue, because I will have more. Don't want to start separate issues, though. Would rather keep them here with the treatment as comments until we're exhausted.)

"Usage" does not have same economic meaning in the cited examples: it has different effects on the resource.

Usage of the bus may put some wear and tear on the bus, but the bus usually survives the event.

Likewise the driver and the motorway, although their contributions and experiences are different from each other and the bus if you go down a level in details.

The diesel fuel does not survive the event. It is consumed.

The passenger is carried from origin to destination and I like the Benefit in the @type there. (@fosterlynn, we should figure out how that would be modeled in REA in sufficient detail to match elf's jsonld.) 

Anyway, to make economic sense of the situation, we need to differentiate those usages. In the NRP vocab, we do that via EventType. Although the name could be changed, and we've thought about changing it to something like EventBehavior, the concept is necessary. IPOTables will need it as well.

I may have more issues as I think about it more, but I agree with @ahdinosaur, this is great progress!

**Comment by elf-pavlik** [comment]
> "Usage" does not have same economic meaning in the cited examples: it has different effects on the resource.
> 
> Usage of the bus may put some wear and tear on the bus, but the bus usually survives the event.
> 
> Likewise the driver and the motorway, although their contributions and experiences are different from each other and the bus if you go down a level in details.
> 
> The diesel fuel does not survive the event. It is consumed.

Thank you @bhaugen for good feedback! I had some mistakes in JSON-LD and I fixed them now.

Regarding usage vs. consumption I created this issue: https://github.com/valueflows/resource/issues/10

If we use particular 200L of fuel which we burned as entity we link to in a graph, than we have clear consumption. If we use a Pool of fuel than we may see it as usage, similar to wear of the bus or highway (micro consumption during usage?)

I think we will need to find way to model all those nuances, and make sure that we clearly explain what each entity in a graph represents, which I did fail with in this example...

Also carrier, passengers, bus fleet manager, motorway manager, petrol pool manager etc. All will log things from their perspectives, using different apps and put emphasis in different aspects of those happenings. In the end it all needs to integrate nicely and handle issues like  https://github.com/valueflows/agent/issues/7

**Comment by bhaugen** [comment]
@elf-pavlik 

> I had some mistakes in JSON-LD and I fixed them now.

Ok, I see you added Consumption to the fuel event. Thanks. The petrol pool manager will appreciate it, too.

My fave different event behavior is Citation. Consumption decrements the quantity of the resource, and thus its total value. Citation does not affect the quantity of the resource, but increases its value.

**Pull request merged**
