### PR TITLE
related Service and Process

### PR DESCRIPTION
**Pull request by elf-pavlik**
This PR treats Work and Service in equal way. We can see both individual and group agents as vf:Process (or distinguish their default process if needed #16). We often call input Work and output Service but to have seamless IPO chains we should treat this type of resource equally on input and output.

I can happily change give/receive terminology to something else, just something to start with and reflect in modeling Work/Service as resource https://github.com/valueflows/resource/issues/15

I also changed direction of arrows in VOWL, it should show direction of predicate (directed labelled edge in a graph) and not our interpretation of represented value flow.

### CODE REVIEW

**Comment by fosterlynn** [comment]
But the creation of a service often has other inputs besides work.  Equipment, space are frequent examples.

**Comment by elf-pavlik** [comment]
Yes, and when we do work we also use tools, eg. I wear glasses, if I don't have proper glasses I can't do any computer work (provide a service)

I define here _vf:Service_ as more specific _vf:Resource_ which one can relate to _vf:Process_ with _vf:receive_ (sub of _vf:inflow_) and _vf:give_ (sub of _vf:outflow_)

R - inflow - P - outflow - R
S - receive - P - give - S

In case of bus trip, a person driving the bus might only drive or might also do small repairs. Another driver might only drive and even from minor repair call specialized service provider (another agent). The process actually gets services on input: driving service & repair service.

**Comment by fosterlynn** [comment]
> Yes, and when we do work we also use tools, eg. I wear glasses, if I don't have proper glasses I can't do any computer work (provide a service)

To be more clear: I'm not counting that I have to wear glasses to do work that provides a service.  I'm talking about use cases where the network needs to account for other things besides work to provide a service.  They need to account for them so people can get income for their contributions to those things.  Somewhere I gave a real example from Sensorica of a service of a 3D printing class.  The 3D printer was one of several other inputs besides the work of preparing and giving the class.  The people who contributed money for the printer get something whenever it is used.  There were designs used for the class.  The people who created the designs got citations for them as input to creating the service (class).  There was polymer input to practice creating 3D printed items.  The items were not an output, just the service of the class.

> I define here vf:Service as more specific vf:Resource which one can relate to vf:Process with vf:receive (sub of vf:inflow) and vf:give (sub of vf:outflow)

Why do you want to re-use terms that mean something else in Transfer?  And if you don't want to use them for Transfer, I don't want to use vf:give for vf:Processes because it means something in the REA community, and only related to transfers.

**Comment by elf-pavlik** [comment]
YAML example showing work as vf:Service available in https://github.com/valueflows/valueflows/issues/110#issuecomment-220734960

> Why do you want to re-use terms that mean something else in Transfer? And if you don't want to use them for Transfer, I don't want to use vf:give for vf:Processes because it means something in the REA community, and only related to transfers.

I can change verbs
- _require_ instead of _receive_
- _export_ instead of _give_

I can also just drop vf:Service specific verbs and use more generic _vf:consume_ and _vf:create_

Everyone can also propose other english words or we can just use UUID for now

**Comment by bhaugen** [comment]
I think this PR confuses the work that goes into a process with a service which is delivered by human labor.

The work that goes into a process most likely has been connected to a reciprocal exchange before it became work going into a process. 

For business-as-usual employment, that is when the employer contracts to pay the employee either a salary or an hourly wage or maybe piecework.

For a network like Sensorica, that work is either a gift, or subject to a value equation that might return some compensation. Or not.

In a mutual coordination economy, that work would fit into some set of community agreements about reciprocity chains.

But then the work, which has been covered by some reciprocity agreements (or not), is executed by a human worker as an input to a process. 

While it may be confusing, those are two different things economically.

Please let me know if that explanation makes no sense, and help me explain it better. Because it is closer to correct than many of the alternatives.

**Comment by elf-pavlik** [comment]
> The work that goes into a process most likely has been connected to a reciprocal exchange before it became work going into a process.
> 
> For business-as-usual employment, that is when the employer contracts to pay the employee either a salary or an hourly wage or maybe piecework.
> 
> For a network like Sensorica, that work is either a gift, or subject to a value equation that might return some compensation. Or not.

I think model of process shouldn't depend on particular choice of accounting. I understand that based on different approaches to accounting people may choose to care less or more about some parts of process description. Still we should focus on enabling everyone to describe the process in detail so everyone can choose what to capture and what to ignore.

**Comment by bhaugen** [comment]
> I think model of process shouldn't depend on particular choice of accounting.

It doesn't. Any exchanges for the work are outside the scope of the process. In the process, all the work inputs, whether recipe, plan or reported, do not care how the work is rewarded. In Sensorica, for example, the process does not know anything about the value equation (or equations, could be more than one that could be applied to the same process). Somebody (or some conversation for agreement) decides which equation to use when they have some income to distribute.

**Comment by elf-pavlik** [comment]
Looking at YAML snippet I comment on in https://github.com/valueflows/process/issues/7#issuecomment-221918226

``` yaml
'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:work
        'vf:involvedAgent': ex:Daniel
        'vf:resource':
          '@type': vf:Resource
          'vf:resourceType': ex:3D-design-work
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
        'vf:note': Creating using my CAD tool. Expect to be done before the due date.
```

How it would look different if instead of 'insider job' we would have 'independent service'?

``` yaml
        'vf:resource':
          '@type': vf:Resource
          'vf:resourceType': ex:3D-design-work
```

I don't understand why process description should care how that 3D-design-(work/service) got allocated to it...

**Comment by fosterlynn** [comment]
> How it would look different if instead of 'insider job' we would have 'independent service'?

I will assume that the outside service work was already purchased by the hour, rather than being part of the future distribution of income.  There are some fuzzy lines between inside and outside in the OVN world.  So, here's my attempt:

``` yaml
'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:use??? (not sure what we want to do for services)
        'vf:involvedAgent': ex:Outside Service, Inc.
        'vf:resource':
          '@type': vf:Resource
          'vf:resourceType': ex:3D-design-service
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
```

> I don't understand why process description should care how that 3D-design-(work/service) got allocated to it...

Not sure what you are asking.  The note in this example is just someone coordinating their work with others, giving info while they are working. It's on the rea:EconomicEvent.  (Only one guy working on the process maybe is making is confusing.)

**Comment by fosterlynn** [comment]
> How it would look different if instead of 'insider job' we would have 'independent service'?

Another thought here too.  Everything that was used etc. would be included in one service.  When it is internal work, if you were tracking computer equipment usage, space usage, etc., you would see that as separate rea:EconomicEvents parallel to the work event.  (That would be good to add to the example some day...)

**Comment by elf-pavlik** [comment]
``` yaml
'vf:flow':
      - '@id': ex:input-1
        'vf:date': 2016/3/2
        'vf:verb': vf:use??? (not sure what we want to do for services)
        'vf:involvedAgent': ex:Outside Service, Inc.
        'vf:resource':
          '@type': vf:Resource
          'vf:resourceType': ex:3D-design-service
        'vf:amount':
            '@type': qudt:QuantityValue
            'qudt:unit': unit:Hours
            'qudt:numericValue': 5
```

> I will assume that the outside service work was already purchased by the hour, rather than being part of the future distribution of income.

Why would this matter? No matter if reciprocal _vf:Transfer_ already happened before or will happen after the event/flow described above. Will you reference `ex:input-1` in that _vf:Transfer_ ?

**Comment by fosterlynn** [comment]
> > I will assume that the outside service work was already purchased by the hour, rather than being part of the future distribution of income.
> 
> Why would this matter? No matter if reciprocal vf:Transfer already happened before or will happen after the event/flow described above. 

Sorry, didn't mean to emphasize the reciprocal transfer, it doesn't matter.  This only matters because I'm trying to say that a service can involve a bundled bunch of inputs, which are hidden from the process that uses the service.  The whole service is input to this process as a bundle (output from the service process?)  Work does not.  The question was can you treat work and service in the same way.

> Will you reference ex:input-1 in that vf:Transfer ?

Don't know.

**Comment by elf-pavlik** [comment]
> The whole service is input to this process as a bundle (output from the service process?) Work does not. The question was can you treat work and service in the same way.

I don't agree, as soon as I wear glasses, or wear clothing (maybe special one required by work), or even I just ate before doing the work ( see #16 ) we do have Work as bundle which comes out as output from other process. Let's see it differently, if something goes into input, must have went out of some output - otherwise we have some magic going on. From what output the Work you record as input goes out of?

**Comment by fosterlynn** [comment]
> I don't agree, as soon as I wear glasses, or wear clothing (maybe special one required by work), or even I just ate before doing the work ( see #16 ) we do have Work as bundle which comes out as output from other process.

Well, I admire that you are trying to put the _currently_ hidden reproduction and maintenance of the work force on the same level with the creation of resources in the _currently_ more social(ized) world.  And trying to make it part of the same cycle.  That is how it should be.  I'm not sure we can make our vocabulary that pure.  Would be nice, I guess.

How would you do it?  Get rid of "work" and use only "service"?  

Work does have some special properties in the creation of value, so I see usefulness in knowing what is work (labor).  Some services will involve say a really expensive piece of equipment used by the worker, and some minimal work.  Possibly different than all the work and other resources that went into maintaining the worker, before the work occurred?

**Comment by elf-pavlik** [comment]
> How would you do it? Get rid of "work" and use only "service"? 

I'll take a closer look at your example and will try to write the work input as service going into the process.

**Comment by elf-pavlik** [comment]
I'll rework this PR with 'logical stocks', _availability_ (4D stocks - have time aspect) and _allocations_. Similar to my comment in https://github.com/valueflows/resource/issues/29#issuecomment-239438358

In general if process requires '6 hours of one person repairing bikes'. Often it will not matter if 1 person works for 6 hours or 2 people work 3 hours each. Sometimes in turn people can't load balance that easily eg. driving a vehicle. We could describe 'Work' as service defined by 'type of work' and 'human work hours' plus some constraints on sharing work - but they can also relate to 'type of work'. The 'commit to task' would work as _vf:Allocation_ based on service _availability_. Just as currently for one _nrp:InputPlan_ you can have multiple _nrp:EconomicEvent_. We would have extra sub-layer in planning which for one plan allows multiple allocations. So we have plan - allocation - event. But we need it for all type of input/output resources so we can deal with it in other issue.

**Comment by elf-pavlik** [comment]
I think we can leave it that an instance of _vf:Process_ simply _vf:consume_ and _vf:create_ instances of _vf:ServiceResource_

**Pull request closed without merging**
