### PR TITLE
vf:Port replaces vf:Input and vf:Output

### PR DESCRIPTION
**Pull request by elf-pavlik**
I see this version as improvement over what we currently have in a repo. We should continue to iterate on it with more PRs.

### CODE REVIEW

**Comment by bhaugen** [comment]
I try to  avoid getting fussy with names, but I dislike Port to replace Input and Output intensely, Input and Output have made sense to everybody I have discussed VF with, whereas Port is meaningless.

Input-Process-Output, for example, is a well-known idiom from at least 1980 and probably much earlier.  And currently, in IPOTables as welll asVF. I would reject this PR.

**Comment by elf-pavlik** [comment]
@bhaugen you still can see Input and Output sections under the _verbs_ section. Currently those verbs define if the port acts as input or output. I see need for common parent that represents the n-ary relation between process and resources. We can use it do define domains and ranges of properties that we want to use with that n-ary relation. If you want to have Input.md and Output.md, you can simply add it and write there whatever explanation that you see appropriate. For formal OWL definitions we don't seem to need those two classes.

**Comment by bhaugen** [comment]
The issue is communication to normal people.

**Comment by elf-pavlik** [comment]
We need both, formal definitions that computers can process as well as human friendly narratives. Currently I put focus on the first one but it shouldn't stop anyone from working on the second.

**Comment by bhaugen** [comment]
rea:CommitmentType is my superclass of InputType and OutputType. rea:Commitment is the REA superclass of InputPlan and OutputPlan. Those names have both history and standards organizations behind them. Port has nothing.

**Comment by fosterlynn** [comment]
I have no problem combining the Input and Output (types) into one term.  I also don't like Port, as I said in an issue.  I'll work on a better term.  

This is the nrp:Commitment Type, the rea:Commitment, and the rea:EconomicEvent, true?  Or just one of those?

**Comment by elf-pavlik** [comment]
> This is the nrp:Commitment Type, the rea:Commitment, and the rea:EconomicEvent, true? Or just one of those?

So far [I could write snippets](https://github.com/valueflows/valueflows/issues/132#issuecomment-222365920) using just the verb as binary relation, where I understand you would use nrp:CommitmentType. This pull request describes the n-ary relation which I only needed to use in situations equivalent to where I understand you use rea:Commitment and rea:EconomicEvent.

I think we could use the same n-ary relation also in situations where I understand you would use nrp:CommitmentType

>  I'll work on a better term. 

As [I mentioned in another issue](https://github.com/valueflows/process/issues/18#issuecomment-223447393), this relation also gets used in that planning stage where we have no commitment from another agent - when we just scale the recipe according to desired output (where recipes can scale, making 1 bike from parts wouldn't) and use that plan to cast intents to gather matches from potential providers. Commitments between agents come into play in later stage.

In [your diagram](https://docs.google.com/drawings/d/13NxkdreIQ_0H43H25kBC5ZKYz2QCgfk7XalOXExUK7Q/edit) you use _Input/Output_, if you prefer I could add commit that would rename proposed _vf:Port_ to _vf:InputOrOutput_. We can rename it once we find something that we find more appropriate.

**Comment by fosterlynn** [comment]
> if you prefer I could add commit that would rename proposed vf:Port to vf:InputOrOutput. We can rename it once we find something that we find more appropriate.

I like that a lot better as a place holder term. :+1:

**Comment by elf-pavlik** [comment]
done!

**Pull request merged**
