### PR TITLE
added verbs

### PR DESCRIPTION
**Pull request by fosterlynn**

### CODE REVIEW

**Comment by elf-pavlik** [comment]
how does _cite_ differ from _use_? if i use an open source software not open design spec, do i _use_ it or _cite_ it? what about valueflows vocab, if someone uses it in software, does this person _use_ it or _cite_ it?

**Comment by elf-pavlik** [comment]
i guess it relates to _blocking use_ vs. _non-blocking use_, certain resource you need to block to use them, other resources you can use without blocking it so others can use them at the same time.

**Comment by bhaugen** [comment]
cite has several different behaviors than use:
- does not block other citers at the same time
- no wear and tear on the resource
- makes the resource more valuable

(for example)

**Comment by fosterlynn** [comment]
Yes, use blocks it for that time.  And can degrade it too.  Cite is pretty much for electronic resources like code, docs, designs, where any number of people can "use" them and it has no effect on the resource.  Comes from citing in scientific papers.

**Comment by fosterlynn** [comment]
Also there is different behavior.  Like when you use something, it might be by the hour.  When you cite something you have to give it some other kind of value that says the value it added to your process.

**Comment by fosterlynn** [comment]
ha bob and I crossed

**Comment by fosterlynn** [comment]
person cites VF vocab

**Pull request merged**
